destination: ./_site
username: bharrisau
branch: source

name: bharr
markdown: redcarpet
pygments: true
exclude: ['Rakefile', 'Gemfile', 'Gemfile.lock', 'vendor']
include: ['.travis.yml']
permalink: /:year/:month/:day/:title/
ga: UA-30655099-1
excerpt_separator: <!--excerpt-->
description: "Life and work"
keywords: ['technology', 'mathematics', 'science', 'electronics', 'programming']
